import Nav from '@/components/nav/Nav'
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className='bg-navyBlue'>
          <div className='layout-wrapper m-auto'>
            <div className='py-10'>
              <Nav />
            </div>
            {children}
          </div>
        </body>
    </html>
  )
}
